name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build (with easer feature)
      run: cargo build --features easer --verbose
    - name: Run tests (with easer feature)
      run: cargo test --features easer --verbose
    - name: Run tests (without default features)
      run: cargo test --no-default-features --verbose
    - name: Run tests (without default features, with alloc feature)
      run: cargo test --no-default-features --features alloc --verbose
    - name: Run tests (without default features, with libm feature)
      run: cargo test --no-default-features --features libm --verbose
    - name: Run tests (without default features, with alloc and libm features)
      run: cargo test --no-default-features --features alloc,libm --verbose
